### ISSUE TITLE
Mods: Astra

### ISSUE THREAD

**Issue by DavidNyan10** [Discord-Client-Encyclopedia-Management/Discord3rdparties#33] opened 2022-07-16 10:38 UTC
### Name

Astra

### Link

https://astranika.com/

### Features

[REDACTED]

### Language(s)

[REDACTED]

### Development Status

Active

### Further comments

I know it's a private mod but I think it's worth mentioning here even though no data is available.

**Comment by sehnryr** [comment] 2022-07-16 10:47
Duplicate of #6

**Closed by sehnryr** 2022-07-16 10:47 UTC
Labels: suggestion
